version: '3.4'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    command: jekyll serve --watch --port 3000 --host 0.0.0.0
    working_dir: /usr/src/app
    ports:
      - 80
    volumes:
      - ${STOLOS_REMOTE_DIR}./:/usr/src/app
