title: Stolos Documentation
email: support@sourcelair.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation of Stolos.io.
baseurl: ""
url: "https://docs.stolos.io"

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  hard_wrap: false

collections:
  cli:
    permalink: /cli/:path/
    output: true
  guides:
    permalink: /guides/:path/
    output: true

gems:
  - jekyll-redirect-from

lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false
