title: Stolos Documentation
email: support@sourcelair.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation of Stolos.io.
baseurl: ""
url: "http://docs.stolos.io"

# Build settings
markdown: kramdown

collections:
  cli:
    permalink: /cli/:path/
    output: true
  guides:
    permalink: /guides/:path/
    output: true

gems:
  - jekyll-redirect-from